steps:
- name: node
  entrypoint: npm
  args: ['install']
# - name: node
#   entrypoint: npm
#   args: ['test']
- name: node
  entrypoint: npm
  args: ["run", "create-env"]
  env: 
    - 'HEROKU_DB_HOST = ${_HEROKU_DB_HOST}'
    - 'HEROKU_DB_PORT = ${_HEROKU_DB_PORT}'
    - 'HEROKU_DB_USER = ${_HEROKU_DB_USER}'
    - 'HEROKU_DB_PASSWORD = ${_HEROKU_DB_PASSWORD}'
    - 'HEROKU_DB = ${_HEROKU_DB}'
    - 'HEROKU_DB_DIALECT = ${_HEROKU_DB_DIALECT}'
    - 'GOOGLE_CLIENT_ID = ${_GOOGLE_CLIENT_ID}'
    - 'GOOGLE_ANALYTICS_ID = ${_GOOGLE_ANALYTICS_ID}'
    - 'MONGO_DB_PASSWORD = ${_MONGO_DB_PASSWORD}'


- name: node
  entrypoint: npm
  args: ['run', 'build']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'